/*
 * Todo-Listenverwaltung API
 *
 * API zur Verwaltung von Todo-Listen und deren Einträgen
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: asad.saleem@gmx.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetTodoList404Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetTodoList404ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetTodoList404Response
        //private GetTodoList404Response instance;

        public GetTodoList404ResponseTests()
        {
            // TODO uncomment below to create an instance of GetTodoList404Response
            //instance = new GetTodoList404Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetTodoList404Response
        /// </summary>
        [Fact]
        public void GetTodoList404ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetTodoList404Response
            //Assert.IsType<GetTodoList404Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
